### ISSUE TITLE
Enable cell decorations for debugging in VSCode

### ISSUE THREAD

**Issue by dsyer** [padreati/rapaio-jupyter-kernel#64] opened 2024-08-03 06:42 UTC
I can set break points and debug a Java notebook if I hack the `kernel.json` to add JVM command line arguments, but that's awkward, especially if I might be running multiple notebooks at the same time (they would all need a different remote port to attach the debugger).

I'm not sure how it works, but in a Python notebook the cells get little annotations next to them so you can choose to debug instead of run on the play button. It would be neat if I could do the same with Java.

**Comment by padreati** [comment] 2024-08-04 17:03
When you change `kernel.json` to enable debugging you enable debugging on kernel program. This is different from debugging the code executed in notebook. What you can do is simply debug how kernel works, but not how notebook works. The latter could be done to some extent if while debugging the kernel you step into the jshell code and see how that works, but is far from what you want.

Since the code is executed and hosted by jshell, jshell needs debug support. JShell does not have debug support. There is  [JEP 222: jshell: The Java Shell (Read-Eval-Print Loop)](https://openjdk.java.net/jeps/222). This JEP states in NonGoals section:

> Out of scope are graphical interfaces and debugger support. The JShell API is intended to allow JShell functionality in IDEs and other tools, but the jshell tool is not intended to be an IDE.

This kernel is based on JShell and I do not know any other Java interpreter which can be used. So I don't see an straight forward way t implement that.

At a deeper thought I think there is a way with JShell. We can split all code snippets, maintain a out-of-JShell registry of those snippets, send the snippets sequentially, maintain out-of-JShell a registry with debug bookmarks and related and hook everything. That would mean to create an external wrapper over JShell and control everything. Addaitionally it also implies implementing all of [Jupyter Debugger Protcol][https://jupyter-client.readthedocs.io/en/latest/messaging.html#debug-request). That is an effort of some hundred hours of work. I will give it a thought, but is far from immediate.

**Comment by padreati** [comment] 2024-08-04 17:47
Duplicate of https://github.com/padreati/rapaio-jupyter-kernel/issues/47

**Closed** 2024-08-04 17:47 UTC
Labels: long term projects
